#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d I II III IV V VI VII
bspc monitor HDMI-2 -d VIII IX X

bspc config border_width         2
bspc config window_gap           12
#bspc config top_padding 0
#bspc config bottom_padding 0

bspc config split_ratio          0.52
bspc config border_width         0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bspc config auto_alternate true #
#bspc config auto_cancel true #
#bspc config focused_border_color \#cf0284
#bspc config active_border_color \#5a0075
#bspc config normal_border_color \#5a0075
#bspc config presel_border_color "#9a875f"
#bspc config urgent_border_color "#504339"
#bspc config focused_locked_border_color "#8c644c"
#bspc config normal_frame_opacity 0.0
#bspc config focused_frame_opacity 0.1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^10' state=floating rectangle=1230x724+1943+148
bspc rule -a Pcmanfm state=floating rectangle=1200x720+360+180
bspc rule -a mpv state=fullscreen
bspc rule -a feh state=floating rectangle=1600x900+100+100
bspc rule -a vlc state=floating
bspc rule -a heroic state=floating rectangle=1600x900+160+90
bspc rule -a Lutris state=floating rectangle=1600x900+160+90
bspc rule -a Steam state=floating rectangle=1600x900+160+90
#bspc rule -a terminator -o desktop='^10' state=floating rectangle 100x100+0+0 sticky=on

~/.fehbg
/usr/bin/numlockx on
xinput --set-prop 13 291 -1
xsetroot -cursor_name Sweet-cursors
polybar &
picom --experimental-backends &

