background {
    path = ~/Pictures/night_city_purps.jpg
    blur_passes = 1
}

label {
    text = cmd[update:1000] echo "$(date)"
    position = 0, 80
    halign = center
    valign = center
    font_size = 24
}

input-field {
    size = 200, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    fade_on_empty = false
    placeholder_text = Password...
    hide_input = false
}
