wallpaper {
        monitor = DP-3
        path = ~/Pictures/kaylesideansty.jpg
        fit_mode = fill # cover fill tile contain
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/jap_alphabet.jpg
    fit_mode = fill
}

splash = false
